// ** WARNING ** ENSURE ONLY ONE OBJECT IS EVER 'HERO: TRUE' 

let posts = [
    {
        id: 1,
        title: "Career Changer",
        image: './images/post-1-img.jpg',
        favorited: false,
        tags: ["breaking into tech", "learning", "motivation"],
        date: "2025-12-01",
        hero: true,
        excerpt: "goes here...",
        content: "goes here...",
    },
    {
        id: 2,
        title: "<q>Non-Technical</q>",
        image: './images/post-2-img.jpg',
        favorited: false,
        tags: ["culture", "human skills", "identity"],
        date: "2025-11-14",
        hero: false,
        excerpt: "goes here...",
        content: "goes here...",
    },
    {
        id: 3,
        title: "A New Set of Acronyms",
        image: './images/post-3-img.jpg',
        favorited: false,
        tags: ["transition", "jargon", "learning curve"],
        date: "2025-11-01",
        hero: false,
        excerpt: "goes here...",
        content: "goes here...",
    },
    {
        id: 4,
        title: "Imposter Syndrome",
        image: './images/post-4-img.jpg',
        favorited: false,
        tags: ["mindset", "confidence", "growth"],
        date: "2025-10-14",
        hero: false,
        excerpt: "goes here...",
        content: "goes here...",
    },
    {
        id: 5,
        title: "The Influence of Others",
        image: './images/post-5-img.jpg',
        favorited: false,
        tags: ["community", "mentorship", "advice"],
        date: "2025-10-01",
        hero: false,
        excerpt: "goes here...",
        content: "goes here...",
    },
    {
        id: 6,
        title: "Where to Begin",
        image: './images/post-6-img.jpg',
        favorited: false,
        tags: ["beginner", "learning", "scrimba"],
        date: "2025-09-14",
        hero: false,
        excerpt: "goes here...",
        content: "goes here...",
    },
    {
        id: 7,
        title: "Will AI Replace Me?",
        image: './images/post-7-img.jpg',
        favorited: false,
        tags: ["AI", "engineering", "future of work"],
        date: "2025-09-01",
        hero: false,
        excerpt: "goes here...",
        content: "goes here...",
    },
]

export default posts